---
run_name: test-2           # will prefix every output

# Physical properties
body: earth                 # decide which initial profiles to use
core_radius: 3480           # in km // could actually be read from file
kinematic_visc: 1e7         # fudge parameter?
mantle_temperature: 4000    # in K, kept constant
tbl_thickness: 200          # in km, thermal boundary layer thickness
tbl_conductivity: 5         # in W/m/K

constant_diff: false         #
constant_diff_value: 2e-5   # im m2/s, if constant_diff=false, this won't be used

# Simulation properties
num_points: 200             # size of the grid
tmax: 1000                  # in Ma
snapshot: 10                # snapshot interval, in Ma
