{
    run_name: test,            # will prefix every output
    body: mars,                # decide which initial profiles to use
    tmax: 4500,                # in Ma
    snapshot: 10,              # snapshot interval, in Ma

    # mantle specific paramters
    mantle:
    {
        initial_dtcore: 100,        # K
        density: 3400,              # kg/m3
        specific_heat: 1000,        # J/K/kg
        cond_mantle: 4,             # W/m/K
        cond_crust: 3,              # W/m/K
        thermal_expansivity: 2e-5,  # 1/K
        gravity: 3.7,               # m/s2
        ref_viscosity: 2e19         # Pa s, ref at 1600 K
    },

    # core specific parameters
    core:
    {
        num_points: 200,            # size of the grid
        kinematic_visc: 1e7,        # fudge parameter?
        specific_heat: 840,         # J/kg/K
        constant_diff: true,        #
        constant_diff_value: 1e-5,  # im m2/s, if constant_diff=false, this won't be used
    },

    # mars geometry
    mars:
    {
        radius: 3390e3,              # in m
        core_radius: 1550e3,         # in m
    },

    # earth geometry
    earth:
    {
        radius: 6371e3,              # in m
        core_radius: 3485e3,         # in m
    },
}
